# Generated by Django 5.2.9 on 2026-02-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinarian',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='vet_certificates/'),
        ),
    ]
