# Generated by Django 5.2.9 on 2026-02-23 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_veterinarian_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rescuereport',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='rescuereport',
            name='longitude',
        ),
    ]
