# Generated by Django 5.2.9 on 2026-03-05 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_rescuereport_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VetAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100)),
                ('pet_species', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Bird', 'Bird'), ('Rabbit', 'Rabbit'), ('Fish', 'Fish'), ('Hamster', 'Hamster'), ('Reptile', 'Reptile'), ('Other', 'Other')], max_length=50)),
                ('pet_breed', models.CharField(blank=True, max_length=100, null=True)),
                ('pet_age', models.CharField(max_length=30)),
                ('pet_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], max_length=10)),
                ('pet_weight', models.CharField(blank=True, max_length=20, null=True)),
                ('pet_symptoms', models.TextField()),
                ('pet_photo', models.ImageField(blank=True, null=True, upload_to='appointment_pets/')),
                ('reason', models.TextField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('PaymentDone', 'Payment Done'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('appointment_time', models.TimeField(blank=True, null=True)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('vet_notes', models.TextField(blank=True, null=True)),
                ('payment_done', models.BooleanField(default=False)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='myapp.userprofile')),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='myapp.veterinarian')),
            ],
        ),
    ]
